filter {
  if [log_category] == "host_network_traffic" {
    mutate {
      convert => {
        "rx_bytes_delta" => "integer"
        "tx_bytes_delta" => "integer"
        "window_seconds" => "float"
      }
    }
  }
}